#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, sys, math, os, random, math

BROADCAST = "FFFF"

class Replica:
    def __init__(self, port, id, others):
        self.port = port
        self.id = id
        self.others = others
        self.leader_id = "FFFF"
        self.follower = True
        self.leader = False
        self.candidate = False
        self.election_timeout = random.uniform(1, 2)
        self.term = 1
        self.log = {}
        self.votes = []
        self.voted_for = None
        self.currtime = 0

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('localhost', 0))

        print("Replica %s starting up" % self.id, flush=True)
        hello = { "src": self.id, "dst": BROADCAST, "leader": BROADCAST, "type": "hello" }
        self.send(hello)
        print("Sent hello message: %s" % hello, flush=True)

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), ('localhost', self.port))

    def respond_to_put(self, msg):
        self.log[msg['key']] = msg['value']
        response = {}

        if self.leader_id != self.id:
            response = {"src": str(self.id), "dst": msg['src'], "leader": self.leader_id, "type": "redirect", "MID": msg['MID']} 
        else:
            response = {"src": str(self.id), "dst": msg['src'], "leader": str(self.id), "type": "ok", "MID": msg['MID']}

        self.send(response)

    def respond_to_get(self, msg):
        response = {}
        if self.leader_id != self.id:
            response = {"src": str(self.id), "dst": msg['src'], "leader": self.leader_id, "type": "redirect", "MID": msg['MID']} 
        else:
            value = self.log[msg['key']]
            response = {"src": str(self.id), "dst": msg['src'], "leader": str(self.id), "type": "ok", "MID": msg['MID'], "value": str(value)}
        self.send(response)

    def begin_election(self):
        print("starting new election -------------------------------", flush=True)
        self.voted_for = None
        self.candidate = True
        self.follower = False
        self.leader = False
        self.term+=1

    def send_request_vote_RPC(self):
        request_vote_rpc = {"src": str(self.id),
                "dst": BROADCAST,
                "leader": self.leader_id,
                'type': 'request_vote_rpc',
                'MID': '1',
                "last_log_idx": str(len(self.log)-1),
                "term":self.term}
            
        self.voted_for = self.id
        print("sending vote request '%s'" % (request_vote_rpc,), flush=True)
        self.send(request_vote_rpc)
            
    def send_heartbeat(self):
        heartbeat = {"src": str(self.id), "dst": BROADCAST, "leader": str(self.id), "type": "heartbeat", "term": self.term, "MID": '-1'}
        self.send(heartbeat)

    def analyze_votes(self):
        count = 0
        for vote in self.votes:
            if vote['vote_granted'] == True:
                count+=1
        if count >= math.ceil(len(self.others)/2):
            self.leader = True
            self.candidate = False
            self.follower = False
            self.voted_for = None
            self.leader_id = self.id
            print("I Am the leader!!!", flush=True)
        else:
            self.leader = False
            self.candidate = False
            self.follower = True


    def respond_to_vote_request(self, msg):
        vote_response = False

        if msg['term'] >= self.term and self.voted_for == None:
            vote_response = True
            
        response = {"src": str(self.id), "dst": msg['src'], "leader": self.leader_id, "MID":"1", "type": "vote_response", "vote_granted": vote_response}
        self.send(response)
        self.voted_for = msg['src']

        print("sending vote response '%s'" % (response,), flush=True)


    def handle_heartbeat(self, msg):
        if msg['term'] >= self.term:
            self.election_timeout = random.uniform(1, 2)
            self.votes = []
            self.term = msg['term']
            self.follower = True
            self.leader = False
            self.candidate = False
            self.voted_for = None
            self.leader_id = msg['leader']
            self.currtime = time.time()
        

    # this is only working because we don't need to do another election, the if statement will never pass if leader fails and new election needs to happen
    def handle_vote_response(self, msg):
        self.votes.append(msg)
        if len(self.votes) == len(self.others): # this is not right, we should just analyze if len(self.votes > majority still alive)
            self.analyze_votes()
            self.votes = []

    def run(self):
        self.currtime = time.time()
        while True:
            socks = []
            if self.leader:
                socks = select.select([self.socket], [], [], .5)[0]
            else:
                socks = select.select([self.socket], [], [], self.election_timeout)[0]

            for sock in socks:
                data, addr = sock.recvfrom(65535) 
                msg = data.decode('utf-8')
                msg = json.loads(msg)

                print("Received message '%s'" % (msg,), flush=True)

                if msg['type'] == 'request_vote_rpc':
                    self.respond_to_vote_request(msg)
                elif msg['type'] == 'heartbeat':
                    self.handle_heartbeat(msg)
                elif msg['type'] == 'vote_response' and self.candidate:
                    self.handle_vote_response(msg)
                elif msg['type'] == 'put':
                    self.respond_to_put(msg)
                elif msg['type'] == 'get':
                    self.respond_to_get(msg)

            if self.leader:
                self.send_heartbeat()
                self.election_timeout = random.uniform(1,2)
            elif len(socks) == 0 or time.time() - self.currtime >= self.election_timeout:
                self.begin_election()
                self.send_request_vote_RPC()
                self.election_timeout = random.uniform(1, 2)
                self.currtime = time.time()
                
                


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help="Port number to communicate")
    parser.add_argument('id', type=str, help="ID of this replica")
    parser.add_argument('others', metavar='others', type=str, nargs='+', help="IDs of other replicas")
    args = parser.parse_args()
    replica = Replica(args.port, args.id, args.others)
    replica.run()
